import Head from "next/head";
import Header from "@/components/header/header";
import Footer from "../components/footer/footer";
import SideBar from "../components/sidebar/sidebar";
import MainContent from "../components/mainContent/mainContent";

//import styles from "../dist/output.css";
//import styles from "@/pages/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Daniel&apos;s Portfolio</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="h-screen bg-white w-full flex flex-col space-y-4 md:flex-row md:space-y-0">
        <SideBar />
        <MainContent />
      </div>

      <Footer />
    </>
  );
}
