import { Provider } from 'react-redux';
import store from '../src/store/store';
import Head from "next/head";
import Header from "@/components/header/header";
//import Footer from "../components/footer/footer";
import SideBar from "../components/sidebar/sidebar";
import MainContent from "../components/mainContent/mainContent";
//import helpers from './helpers.js';

export default function Home() {
  //const randomGradient1 = helpers.staticGradient();
  const randomGradient1 = "from-rose-100 via-slate-300 to-teal-100";
  //const randomGradient2 = helpers.staticGradient();
  //<Footer />
  return (
    <>
      <div className={"font-sans bg-gradient-to-br " + randomGradient1} >
        <Provider store={store}>
        <Head>
          <title>Daniel&apos;s Portfolio</title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />          
        </Head>

        <Header />

        <div className="w-full flex flex-col space-y-4 md:flex-row md:space-x-0 md:space-y-0">
          <SideBar />
          <MainContent gradient={randomGradient1}/>
        </div>
        
        </Provider>
      </div>
    </>
  );
}
